### PR TITLE
BACK-1234 Update label account with existing endpoint

### PR DESCRIPTION
**Pull request by mbasire-ledger**
## What is this about?

The `label` account field can be updated with the endpoint
PUT /accounts/{UUID} 
which makles partial update on the given account identified by {UUID}

The body is either
 `{ "sync-frequency" : 300  }` or `{ "label" : "another label" }`

If both fields are present in the body, it will be a "sync frequency" update. 

## Cute picture of lama
lama
ttp

### CODE REVIEW

**Comment by nukky94** [comment]
`If both fields are present in the body, it will be a "sync frequency" update.`

Why not update both ?

**Comment by mbasire-ledger** [comment]
Ok, we may also update both fields. 
I don't think is a real use case but it should be more consistent according to the client of this endpoint.

**Comment by mbasire-ledger** [comment]
Ok, both fields can be updated at the same time too.

**Comment by estrauser-ledger** [comment]
You gonna have to change dat llama or you never gonna get dat approval

**Review by nukky94 — APPROVED** [review]
🚀

**Pull request merged**
